airportData["HND"] = {
    name: "羽田(HND)",
    runWay: "",
    open: ""
}
freqdata.push(
    { group: 'HND', area: 'TWR', section: 'P RWY-A', freq: 118.1 },
    { group: 'HND', area: 'TWR', section: '2 RWY-B', freq: 118.575 },
    { group: 'HND', area: 'TWR', section: '3 RWY-C/RWY23', freq: 124.35 },
    { group: 'HND', area: 'TWR', section: '4 RWY-D', freq: 118.725 },
    { group: 'HND', area: 'TWR', section: '5', freq: 118.8 },
    { group: 'HND', area: 'TWR', section: '6', freq: 126.2 },
    { group: 'HND', area: 'TWR', section: '7', freq: 236.8 },

    { group: 'HND', area: 'APP', section: '01 P羽田エリア', freq: 119.1 },
    { group: 'HND', area: 'APP', section: '02 羽田エリア', freq: 119.4 },
    { group: 'HND', area: 'APP', section: '03', freq: 119.65 },
    { group: 'HND', area: 'APP', section: '04', freq: 119.7 },
    { group: 'HND', area: 'APP', section: '05', freq: 125.4 },
    { group: 'HND', area: 'APP', section: '06', freq: 232.2 },
    { group: 'HND', area: 'APP', section: '07', freq: 261.2 },
    { group: 'HND', area: 'APP', section: '08', freq: 121.275 },
    { group: 'HND', area: 'APP', section: '09 成田エリア', freq: 124.4 },
    { group: 'HND', area: 'APP', section: '10', freq: 125.2 },
    { group: 'HND', area: 'APP', section: '11', freq: 125.8 },
    { group: 'HND', area: 'APP', section: '12 成田エリア', freq: 127.7 },
    { group: 'HND', area: 'APP', section: '13', freq: 225.65 },

    { group: 'HND', area: 'CLR ATIS', section: 'CLR P', freq: 121.825 },
    { group: 'HND', area: 'CLR ATIS', section: 'CLR', freq: 121.875 },
    { group: 'HND', area: 'CLR ATIS', section: 'ATIS', freq: 128.8 },
    { group: 'HND', area: 'RDR', section: '01', freq: 124 },
    { group: 'HND', area: 'RDR', section: '02 羽田エリア', freq: 126.5 },
    { group: 'HND', area: 'RDR', section: '03', freq: 236.8 },
    { group: 'HND', area: 'RDR', section: '04', freq: 261.2 },
    { group: 'HND', area: 'RDR', section: '05', freq: 295.9 },
    { group: 'HND', area: 'RDR', section: '06 成田エリア', freq: 120.2 },
    { group: 'HND', area: 'RDR', section: '07', freq: 119.025 },
    { group: 'HND', area: 'RDR', section: '08', freq: 120.9 },
    { group: 'HND', area: 'RDR', section: '09', freq: 123.6 },
    { group: 'HND', area: 'RDR', section: '10', freq: 125.1 },
    { group: 'HND', area: 'RDR', section: '11', freq: 283.4 },
    { group: 'HND', area: 'DEP', section: '01 P羽田エリア', freq: 126 },
    { group: 'HND', area: 'DEP', section: '02 羽田エリア', freq: 120.8 },
    { group: 'HND', area: 'DEP', section: '03', freq: 127.6 },
    { group: 'HND', area: 'DEP', section: '04 成田エリア', freq: 124.2 },
    { group: 'HND', area: 'DEP', section: '05 成田エリア', freq: 119.6 },
    { group: 'HND', area: 'DEP', section: '06', freq: 120.6 },
    { group: 'HND', area: 'DEP', section: '07', freq: 125.525 },
    { group: 'HND', area: 'TCA', section: '01 羽田エリア', freq: 124.75 },
    { group: 'HND', area: 'TCA', section: '02', freq: 119.7 },
    { group: 'HND', area: 'TCA', section: '03', freq: 256.1 },
    { group: 'HND', area: 'TCA', section: '04 成田エリア', freq: 119.45 },
    { group: 'HND', area: 'TCA', section: '05', freq: 246.1 },
    { group: 'HND', area: 'GND', section: '01 T2エリア', freq: 118.225 },
    { group: 'HND', area: 'GND', section: '02 T3エリア', freq: 121.625 },
    { group: 'HND', area: 'GND', section: '03 T1エリア', freq: 121.7 },
    { group: 'HND', area: 'GND', section: '03 RWY-Dエリア', freq: 121.975 },
    { group: 'HND', area: 'GND', section: '04 貨物・特別地区', freq: 122.075 },
);